### ISSUE TITLE
Unrecognized function or variable 'srgtsFitCreateState'.

### ISSUE THREAD

**Issue by blankjul** [ahsanulhabib/HSMEA#1]
Thank you for making your research publicly available. I was trying to run the `Multirun_HSMEA` and am facing the following issue:
```
Unrecognized function or variable 'srgtsFitCreateState'.

Error in srgtsRBFFit (line 62)
        srgtSTT = srgtsFitCreateState(srgtOPT);

Error in rbf_train (line 3)
rbf_model = srgtsRBFFit(options);

Error in TrainMultiSurrogate>train_single_model (line 108)
            model_crossval = feval(train_func, x(t_ids_mod,:), f(t_ids_mod,:));

Error in TrainMultiSurrogate>train_model (line 51)
        [model_data{i}, model_nrmse{i}] = train_single_model(x, f, t_ids, v_ids, model_type, Theta);

Error in TrainMultiSurrogate (line 40)
surrogate = train_model(surrogates, x_train, f_train, t_ids, v_ids, Theta);

Error in HSMEA (line 98)
        dmodel     = TrainMultiSurrogate(Global,A2.decs,f_train(:,m),THETAobj(m,:));
```

(MacOSX 12.0.1, Matlab R2020b)

Is there any import I am missing or another library I need to install?

**Comment by blankjul** [comment]
As a quick fixed I have removed `rbf` from the surrogate list which makes the error above disappear. (it still would be good to actually fix it to reproduce the results).

However, the code then gets stuck 

```
Error using EfficientNDSort_c (line 9)
Undefined function 'EfficientNDSort' for input arguments of type 'double'.

Error in NDRankOne (line 26)
            [id,fr] = EfficientNDSort_c(set1);%dom = nd_sort_min(set1, M, N);

Error in InfillSelection (line 67)
        [ChildObjRank1,Rank1ID] = NDRankOne(ChildObjFeas);

Error in HSMEA (line 194)
        [ChildSelDec,RestDec,CVeps] =
        InfillSelection(Global,A2,Model,PopDec,PopObj,PopCV,CVeps,mu,Vi,Vn,Zmin,Zmax);

Error in Multirun_HSMEA (line 72)
    parfor r = 1:numel(Runpaths)

```

**Comment by ahsanulhabib** [comment]
> Thank you for making your research publicly available. I was trying to run the `Multirun_HSMEA` and am facing the following issue:
> 
> ```
> Unrecognized function or variable 'srgtsFitCreateState'.
> 
> Error in srgtsRBFFit (line 62)
>         srgtSTT = srgtsFitCreateState(srgtOPT);
> 
> Error in rbf_train (line 3)
> rbf_model = srgtsRBFFit(options);
> 
> Error in TrainMultiSurrogate>train_single_model (line 108)
>             model_crossval = feval(train_func, x(t_ids_mod,:), f(t_ids_mod,:));
> 
> Error in TrainMultiSurrogate>train_model (line 51)
>         [model_data{i}, model_nrmse{i}] = train_single_model(x, f, t_ids, v_ids, model_type, Theta);
> 
> Error in TrainMultiSurrogate (line 40)
> surrogate = train_model(surrogates, x_train, f_train, t_ids, v_ids, Theta);
> 
> Error in HSMEA (line 98)
>         dmodel     = TrainMultiSurrogate(Global,A2.decs,f_train(:,m),THETAobj(m,:));
> ```
> 
> (MacOSX 12.0.1, Matlab R2020b)
> 
> Is there any import I am missing or another library I need to install?

**Comment by ahsanulhabib** [comment]
Regarding:
> ```
> Unrecognized function or variable 'srgtsFitCreateState'.
> 
> Error in srgtsRBFFit (line 62)
>         srgtSTT = srgtsFitCreateState(srgtOPT);
> 
> Error in rbf_train (line 3)
> rbf_model = srgtsRBFFit(options);
> 
> Error in TrainMultiSurrogate>train_single_model (line 108)
>             model_crossval = feval(train_func, x(t_ids_mod,:), f(t_ids_mod,:));
> 
> Error in TrainMultiSurrogate>train_model (line 51)
>         [model_data{i}, model_nrmse{i}] = train_single_model(x, f, t_ids, v_ids, model_type, Theta);
> 
> Error in TrainMultiSurrogate (line 40)
> surrogate = train_model(surrogates, x_train, f_train, t_ids, v_ids, Theta);
> 
> Error in HSMEA (line 98)
>         dmodel     = TrainMultiSurrogate(Global,A2.decs,f_train(:,m),THETAobj(m,:));
> ```
> 
> (MacOSX 12.0.1, Matlab R2020b)
> 
> Is there any import I am missing or another library I need to install?

I have uploaded a new folder named "tools" under HSMEA/Surrogates
Please download the folder and keep it in your MATLAB path. This should solve the issue.

Regarding:
> ```
> Error using EfficientNDSort_c (line 9)
> Undefined function 'EfficientNDSort' for input arguments of type 'double'.
> 
> Error in NDRankOne (line 26)
>             [id,fr] = EfficientNDSort_c(set1);%dom = nd_sort_min(set1, M, N);
> 
> Error in InfillSelection (line 67)
>         [ChildObjRank1,Rank1ID] = NDRankOne(ChildObjFeas);
> 
> Error in HSMEA (line 194)
>         [ChildSelDec,RestDec,CVeps] =
>         InfillSelection(Global,A2,Model,PopDec,PopObj,PopCV,CVeps,mu,Vi,Vn,Zmin,Zmax);
> 
> Error in Multirun_HSMEA (line 72)
>     parfor r = 1:numel(Runpaths)
> ```

I believe you need to MEX the EfficientNDSort.c provided in HSMEA/Public folder with a MacOS supported compiler.

Please see page 5 of https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2020b-supported-compilers.pdf for supported compilers for your system.

Please let me know if the abovementioned solutions worked. I will close the issue accordingly.

**Comment by blankjul** [comment]
Thanks for your quick help. I got it to work!
(I had to remove the malloc.h line for compilation. malloc seems to be deprecated)

The new Surrogate folder makes `rbf` work as well.

Thanks again.
